# Generated by Django 4.0.3 on 2022-12-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_booking_option_alter_order_amount_of_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='emission_saved',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
