# Generated by Django 4.0.3 on 2022-12-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_emission_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='emission_saved',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
