# Generated by Django 4.0.3 on 2022-12-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_emission_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount_of_tickets',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
