# Generated by Django 4.0.3 on 2022-12-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_amount_of_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount_of_tickets',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
