# Generated by Django 4.0.3 on 2022-11-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalenderEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=25)),
                ('category', models.CharField(max_length=250)),
                ('departure_date', models.DateTimeField()),
                ('arrival_date', models.DateTimeField()),
            ],
        ),
    ]
