# Generated by Django 4.0.3 on 2022-11-18 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_bookingentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibleStationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='compatible_stations',
            field=models.ManyToManyField(blank=True, through='stations.CompatibleStationLink', to='stations.station'),
        ),
        migrations.AddField(
            model_name='compatiblestationlink',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stations.station'),
        ),
        migrations.AddField(
            model_name='compatiblestationlink',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stations.station'),
        ),
    ]
