# Generated by Django 4.0.3 on 2022-12-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_bookingentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalenderEntry',
        ),
    ]
