# Generated by Django 4.0.3 on 2022-11-18 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_compatiblestationlink_station_compatible_stations_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalenderEntry',
        ),
    ]
