# Generated by Django 4.0.3 on 2023-01-09 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_delete_calenderentry'),
        ('stations', '0006_delete_calenderentry'),
    ]

    operations = [
    ]
